IdentityConv:
  attributes:
    group:
      datatype: int32
    kernel_shape:
      datatype: int32[]
    pads:
      datatype: int32[]
    strides:
      datatype: int32[]
  inputs:
    tpg_input_0:
      shape: 1x3x480x960
    tpg_input_1:
      shape: 3x1x1x1
  outputs:
    tpg_output_0:
      shape: 1x3x480x960
  plugin_type: IPluginV2DynamicExt
  support_format_combination:
  - "float32+float32+float32"
  - "float16+float32+float32"
